### ISSUE TITLE
Install fails because module 'is-property' isn't installed

### ISSUE THREAD

**Issue by frankhale** [mafintosh/electron-prebuilt#40]
I think electron-prebuilt needs to include a dependency on module is-property because on my system it's bombing out and can't install because that module is missing. After I manually installed is-property electron-prebuilt installed correctly. 

```
C:\Users\Frank\Desktop>npm install -g electron-prebuilt
C:\Users\Frank\AppData\Roaming\npm\electron -> C:\Users\Frank\AppData\Roaming\np
m\node_modules\electron-prebuilt\cli.js

> electron-prebuilt@0.27.3 postinstall C:\Users\Frank\AppData\Roaming\npm\node_m
odules\electron-prebuilt
> node install.js

module.js:334
    throw err;
          ^
Error: Cannot find module 'is-property'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Frank\AppData\Roaming\npm\node_modules\elect
ron-prebuilt\node_modules\electron-download\node_modules\nugget\node_modules\req
uest\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\gener
ate-object-property\index.js:1:80)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\node
_modules\\npm\\bin\\npm-cli.js" "install" "-g" "electron-prebuilt"
npm ERR! node v2.2.1
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.27.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.27.3 postinstall script 'node install
.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Frank\Desktop\npm-debug.log
```

**Comment by frankhale** [comment]
This happened to me on two different Windows machines.

**Comment by maxogden** [comment]
@frankhale thanks for the bug report. This is super weird behavior. @mafintosh have you ever seen this before?

**Comment by justinmchase** [comment]
:+1:

**Comment by justinmchase** [comment]
As a work-around you can just install is-property globlally and then it will work: `npm install is-property -g`

**Comment by gcoupelant** [comment]
+1 @justinmchase tip worked

**Comment by mafintosh** [comment]
what version of npm are you using? this should never happen as is-property is a dependency of generate-object-property (which is throwing this error)

**Comment by frankhale** [comment]
Not sure exact version of npm but I was using iojs 2.2.1 at the time.

**Comment by frankhale** [comment]
Actually it's in the log message posted above:

```
npm ERR! node v2.2.1
npm ERR! npm  v2.11.0
```

**Comment by gcoupelant** [comment]
Same with me, io.js installed with chocolatey on Windows 10
node v2.2.1 and npm v2.11.0

**Comment by mafintosh** [comment]
@frankhale @gcoupelant this seems to be an npm issue. is this reproducible on subsequent installs?

**Comment by frankhale** [comment]
I'll see if I can reproduce it using iojs 2.3.0 as soon as I have time today.

**Comment by dominhhai** [comment]
Same with me in Win 7 - 64 bit, and iojs 2.2.1.

**Comment by v12** [comment]
Experiencing same issue:
* **Platform**: Win 8.1 x64
* **io.js**: v2.3.0
* **npm**: v2.11.1

**Comment by maxogden** [comment]
I think this is a windows specific issue because we are using too many modules and windows paths have a hard limit on length. I'll look into a fix

**Comment by v12** [comment]
@maxogden you're right, seems to be io.js bug, which was introduced in v2.2.0 (https://github.com/nodejs/io.js/pull/1801) and fixed in v2.3.1 (https://github.com/nodejs/io.js/commit/a4f4909f3d15dbc02f4742ad168afbe11d6d8dc4).

If you use any version of io.js in-between **2.2.0** and **2.3.0** inclusive, it fails to load any module that has path length greater than 259 characters in those versions.

**Comment by frankhale** [comment]
Thanks @v12 for this information! I removed electron-prebuilt, removed is-property, installed iojs 2.3.1 and then reinstalled electron-prebuilt and it installed without issue.

**Comment by snowcxt** [comment]
I'm using node v4.0.0. I still have this problem on my Windows.

**Comment by frankhale** [comment]
@snowcxt, try installing the is-property module and then install electron-prebuilt and see if that works.

**Comment by snowcxt** [comment]
I tried that. Didn't work for me. BTW I only get this error when I use Request

**Comment by justinmchase** [comment]
@snowcxt  You tried to install it globally? Like this: https://github.com/mafintosh/electron-prebuilt/issues/40#issuecomment-113556938

**Comment by snowcxt** [comment]
You mean `npm install is-property -g`? Yes
