### ISSUE TITLE
Error: EEXIST: file already exists, symlink 'Versions/Current/Electron Framework' -> '.../node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework'

### ISSUE THREAD

**Issue by MathijsvVelde** [mafintosh/electron-prebuilt#78]
Hello fellow programers,

I'm using 'electron-prebuilt' together with 'electron-rebuild', but every time now when I run ```$ ./node_modules/.bin/electron-rebuild``` or directly ```$ node ./node_modules/electron-prebuilt/install.js``` I get this ERROR :cry: 
```shell
$ node ./node_modules/electron-prebuilt/install.js
.../app/node_modules/electron-prebuilt/install.js:15
  throw err
  ^

Error: EEXIST: file already exists, symlink 'Versions/Current/Electron Framework' -> '.../app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework'
    at Error (native)
```

After doing [this](https://github.com/mafintosh/electron-prebuilt/pull/77)
```shell
.../app/node_modules/electron-prebuilt/install.js:15
  throw new Error(err)
  ^

Error: Error: EEXIST: file already exists, symlink 'Versions/Current/Electron Framework' -> '.../app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework'
    at onerror (.../app/node_modules/electron-prebuilt/install.js:15:9)
    at .../app/node_modules/electron-prebuilt/install.js:35:23
    at Object.callback (.../app/node_modules/extract-zip/index.js:53:20)
    at .../app/node_modules/async/lib/async.js:901:35
    at _arrayEach (.../app/node_modules/async/lib/async.js:85:13)
    at .../app/node_modules/async/lib/async.js:893:17
    at .../app/node_modules/async/lib/async.js:44:16
    at .../app/node_modules/extract-zip/index.js:154:19
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Apparently `install.js` can't be run twice (for a possible needed reinstallation)

How to fix?

Thanks.

**Comment by mafintosh** [comment]
This should now be fixed in master and will be released with the next version of electron

**Comment by pouyakary** [comment]
@mafintosh we're still facing the problem within electron `5.0.5` and the these workspace tools:

```
{
    "electron": "^5.0.5",
    "electron-builder": "^20.44.4",
    "electron-devtools-installer": "^2.2.4",
    "electron-log": "^3.0.6",
    "electron-updater": "^4.0.6"
}
```
